### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by CCERocks** [LingDong-/linedraw#1]
Hi there.. its seem Python 2 will be dead on Jan 2020.. any tweak for this code to be run on Python 37 ?

**Comment by LingDong-** [comment]
I just tweaked the code so it runs for both python2 and python3.

See commit: https://github.com/LingDong-/linedraw/commit/2cfeb04e0da585c4e0bbba04c587d50cf5bcc39e

Mostly just adding parentheses around print statements and using `//` for integer division.
Tested a bit on python 2.7.15 and 3.7.4, and everything seems to work.
If you find any problems please let me know.

Thanks

**Comment by CCERocks** [comment]
lol.. im putting ( ) when following the error.. but then there is more to that..

thank you very much for the code.
