### ISSUE TITLE
input file from webcam capture?

### ISSUE THREAD

**Issue by CCERocks** [LingDong-/linedraw#2]
Hi is this possible to merge or run a bot to check folder that have the image file as input ? 

i found this python script to capture webcam photo.. https://github.com/kevinam99/capturing-images-from-webcam-using-opencv-python 

im on windows but then i dont know how to run bash both your script after the 1st script.

**Comment by LingDong-** [comment]
Hi, you can try the simple script below, which checks contents of a given folder every second, processes any new images it finds, and saves the results as SVG's with the same base filenames.

You might want to change the `path` variable to point to your desired folder, and change `time.sleep(x)` to the desired time interval.

```python
import time
from glob import glob
import linedraw

path = "./frames/*.jpg"

f_old = glob(path);

while True:
	f_now = glob(path)
	f_new = [x for x in f_now if (x not in f_old)]

	if len(f_new):
		print("processing new files:",f_new)
	else:
		print("no new file found.")

	for f in f_new:
		linedraw.export_path = f.replace(".jpg",".svg")
		linedraw.sketch(f)

	f_old = f_now
	time.sleep(1)
```

**Comment by CCERocks** [comment]
thank you very much for the code.

best regards
