### ISSUE TITLE
Please: Error Message .

### ISSUE THREAD

**Issue by Mannilab** [LingDong-/linedraw#6]
After an apparent regular generation of paths:

generating contours...
finding edges...
getting contour points...
connecting contour points...
getting contour points...
connecting contour points...
hatching...
optimizing stroke sequence...

I get the following error message:

Traceback (most recent call last):
  File "/Users/massimomanni/Documents/linedrawx.py", line 3, in <module>
    lines = linedraw.sketch("/Users/massimomanni/Desktop/images.jpg/cigno.bmp")  # return list of polylines, eg.
  File "/Users/massimomanni/Documents/linedraw.py", line 201, in sketch
    f = open(export_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: 'output/out.svg'
>>>

**Comment by LingDong-** [comment]
Hi, 
I think you either need to provide an output path, e.g. with `-o my/path/to/output.svg`, or create a folder named `output`, so that the default output path exists.

**Comment by Mannilab** [comment]
Thanks, now it works great -! just specify the export folder as suggested!


Il Sab 10 Lug 2021, 05:28 Lingdong Huang ***@***.***> ha
scritto:
